version: "3.8"
services:
  node:
    image: "node:18"
    user: "node"
    working_dir: /home/node/app
    depends_on:
      - mysql
    environment:
      - PORT=5001
      - NODE_ENV=production
      - DB_HOST=mysql
      - DB_USER=root
      - DB_PASSWORD=root
      - DB_DATABASE=docker
      - DB_PORT=3306
    volumes:
      - ./:/home/node/app
    ports:
      - "5001:5001"
    command: "npm start"
  mysql:
    image: "mysql:latest"
    restart: always
    volumes:
      - ./mysql/:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=docker
    ports:
      - "3306:3306"
  phpmyadmin:
    image: "phpmyadmin/phpmyadmin:latest"
    depends_on:
      - mysql
    environment:
      - PMA_ARBITRARY=1
    restart: always
    links:
      - "mysql:db"
    ports:
      - "8182:80"
  client:
    build:
      context: ./client
    ports:
      - "5173:5173"
    volumes:
      - ./client:/client
      - /client/node_modules